// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFlow.Infrastructure.Integrations;

#nullable disable

namespace PropFlow.Infrastructure.Persistence.Migrations.Integrations
{
    [DbContext(typeof(IntegrationStore))]
    partial class IntegrationStoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("integrations")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFlow.Domain.Integrations.Conflict", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentValue")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FirstSeenInRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastSeenInRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("integer");

                    b.Property<string>("ObservedValue")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "LastSeenInRunId");

                    b.HasIndex("OrganizationId", "ConnectionId", "Status", "LastSeenAt")
                        .IsDescending(false, false, false, true);

                    b.HasIndex("OrganizationId", "ConnectionId", "Kind", "ExternalId", "Reason", "Field")
                        .IsUnique()
                        .HasDatabaseName("IX_Conflicts_OpenDivergence")
                        .HasFilter("\"Status\" = 'Open'");

                    b.ToTable("Conflicts", "integrations");
                });

            modelBuilder.Entity("PropFlow.Domain.Integrations.ExternalRecordLink", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("InternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastReconciledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReconciledHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RetiredByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "ConnectionId", "LastRunId");

                    b.HasIndex("OrganizationId", "ConnectionId", "SyncState");

                    b.HasIndex("OrganizationId", "Kind", "InternalId");

                    b.HasIndex("OrganizationId", "ConnectionId", "Kind", "ExternalId")
                        .IsUnique();

                    b.ToTable("RecordLinks", "integrations");
                });

            modelBuilder.Entity("PropFlow.Domain.Integrations.IntegrationConnection", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastSucceededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "SourceSystem")
                        .IsUnique();

                    b.ToTable("Connections", "integrations");
                });

            modelBuilder.Entity("PropFlow.Domain.Integrations.MappingProfile", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefaultCreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultTimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("TargetPortfolioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "ConnectionId", "Kind")
                        .IsUnique();

                    b.ToTable("MappingProfiles", "integrations");
                });

            modelBuilder.Entity("PropFlow.Domain.Integrations.MappingRule", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceField")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "ProfileId", "SourceField");

                    b.ToTable("MappingRules", "integrations");
                });

            modelBuilder.Entity("PropFlow.Domain.Integrations.SyncRun", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Added")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Conflicted")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Failed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Seen")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Updated")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "ConnectionId")
                        .IsUnique()
                        .HasDatabaseName("IX_SyncRuns_ActiveClaim")
                        .HasFilter("\"Status\" = 'Running'");

                    b.HasIndex("OrganizationId", "ConnectionId", "StartedAt")
                        .IsDescending(false, false, true);

                    b.HasIndex("OrganizationId", "Status", "HeartbeatAt");

                    b.ToTable("SyncRuns", "integrations");
                });

            modelBuilder.Entity("PropFlow.Domain.Integrations.Conflict", b =>
                {
                    b.HasOne("PropFlow.Domain.Integrations.IntegrationConnection", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Integrations.ExternalRecordLink", b =>
                {
                    b.HasOne("PropFlow.Domain.Integrations.IntegrationConnection", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Integrations.MappingProfile", b =>
                {
                    b.HasOne("PropFlow.Domain.Integrations.IntegrationConnection", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Integrations.MappingRule", b =>
                {
                    b.HasOne("PropFlow.Domain.Integrations.MappingProfile", null)
                        .WithMany("Rules")
                        .HasForeignKey("OrganizationId", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Integrations.SyncRun", b =>
                {
                    b.HasOne("PropFlow.Domain.Integrations.IntegrationConnection", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Integrations.MappingProfile", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
