// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFlow.Infrastructure.Persistence;

#nullable disable

namespace PropFlow.Infrastructure.Persistence.Migrations.Operations
{
    [DbContext(typeof(OperationsStore))]
    [Migration("20260911164429_FS_S04LeadSource")]
    partial class FS_S04LeadSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("operations")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFlow.Domain.Assets.Asset", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("ExpectedServiceLifeYears")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("InstalledOn")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ReplacementCostEstimate")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("WarrantyExpiresOn")
                        .HasColumnType("date");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "PropertyId");

                    b.HasIndex("OrganizationId", "SpaceId");

                    b.ToTable("Assets", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Assets.RepeatRepairPolicy", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("MatchByCategory")
                        .HasColumnType("boolean");

                    b.Property<int>("RepairThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("WindowDays")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("RepeatRepairPolicies", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Automation.AutomationRule", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "IsEnabled", "Trigger");

                    b.ToTable("AutomationRules", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Communications.Announcement", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "Status", "ExpiresAt");

                    b.ToTable("Announcements", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Leasing.Lease", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateOnly?>("MoveOutOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NoticeDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SecurityDeposit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "ResidentId", "Status");

                    b.HasIndex("OrganizationId", "SpaceId", "Status");

                    b.ToTable("Leases", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Leasing.LeaseNotice", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "LeaseId");

                    b.HasIndex("OrganizationId", "Status", "DueOn");

                    b.ToTable("LeaseNotices", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Marketing.Inquiry", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("LeadSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProspectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "ListingId", "Email", "Status");

                    b.ToTable("Inquiries", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Marketing.Listing", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AvailableOn")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("MonthlyRent")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "PropertyId");

                    b.HasIndex("OrganizationId", "SpaceId");

                    b.HasIndex("OrganizationId", "Status", "AvailableOn");

                    b.ToTable("Listings", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Marketing.Showing", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProspectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "ListingId", "ScheduledAt");

                    b.ToTable("Showings", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.People.Employee", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("OrganizationId", "Id");

                    b.ToTable("Employees", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.People.Occupancy", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("MovedInOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MovedOutOn")
                        .HasColumnType("date");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "ResidentId");

                    b.HasIndex("OrganizationId", "SpaceId");

                    b.ToTable("Occupancies", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.People.Resident", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("EmailConsent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("EmailConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SmsConsent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("SmsConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId", "Id");

                    b.ToTable("Residents", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.People.Vendor", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Trade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OrganizationId", "Id");

                    b.ToTable("Vendors", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Building", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "PropertyId");

                    b.ToTable("Buildings", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Portfolio", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("OrganizationId", "Id");

                    b.ToTable("Portfolios", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Property", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "PortfolioId");

                    b.ToTable("Properties", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Space", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "BuildingId");

                    b.HasIndex("OrganizationId", "PropertyId");

                    b.ToTable("Spaces", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Timeline.TimelineEntry", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OldValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("RelatedObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedObjectType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("ResidentVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "WorkId", "OccurredAt");

                    b.ToTable("Timeline", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Work.Attachment", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<bool>("ResidentVisible")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RetainUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "RetainUntil");

                    b.HasIndex("OrganizationId", "WorkId", "CreatedAt");

                    b.ToTable("Attachments", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Work.SavedView", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Columns")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "UserId", "IsDefault");

                    b.HasIndex("OrganizationId", "UserId", "Name")
                        .IsUnique();

                    b.ToTable("SavedViews", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Work.WorkCategory", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("WorkCategories", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Work.WorkItem", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResidentVisibleNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("ScheduledEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ScheduledStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("WorkType")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "AssetId");

                    b.HasIndex("OrganizationId", "BuildingId");

                    b.HasIndex("OrganizationId", "CategoryId");

                    b.HasIndex("OrganizationId", "EmployeeId");

                    b.HasIndex("OrganizationId", "PropertyId");

                    b.HasIndex("OrganizationId", "SpaceId");

                    b.HasIndex("OrganizationId", "VendorId");

                    b.ToTable("WorkItems", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Assets.Asset", b =>
                {
                    b.HasOne("PropFlow.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropFlow.Domain.Properties.Space", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PropFlow.Domain.Leasing.Lease", b =>
                {
                    b.HasOne("PropFlow.Domain.People.Resident", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropFlow.Domain.Properties.Space", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Leasing.LeaseNotice", b =>
                {
                    b.HasOne("PropFlow.Domain.Leasing.Lease", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "LeaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Marketing.Inquiry", b =>
                {
                    b.HasOne("PropFlow.Domain.Marketing.Listing", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Marketing.Listing", b =>
                {
                    b.HasOne("PropFlow.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropFlow.Domain.Properties.Space", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PropFlow.Domain.Marketing.Showing", b =>
                {
                    b.HasOne("PropFlow.Domain.Marketing.Listing", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.People.Occupancy", b =>
                {
                    b.HasOne("PropFlow.Domain.People.Resident", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropFlow.Domain.Properties.Space", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Building", b =>
                {
                    b.HasOne("PropFlow.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Property", b =>
                {
                    b.HasOne("PropFlow.Domain.Properties.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Space", b =>
                {
                    b.HasOne("PropFlow.Domain.Properties.Building", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Timeline.TimelineEntry", b =>
                {
                    b.HasOne("PropFlow.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "WorkId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PropFlow.Domain.Work.Attachment", b =>
                {
                    b.HasOne("PropFlow.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Work.WorkItem", b =>
                {
                    b.HasOne("PropFlow.Domain.Assets.Asset", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Domain.Properties.Building", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Domain.Work.WorkCategory", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Domain.People.Employee", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropFlow.Domain.Properties.Space", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Domain.People.Vendor", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VendorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
