// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFlow.Infrastructure.Persistence;

#nullable disable

namespace PropFlow.Infrastructure.Persistence.Migrations.Operations
{
    [DbContext(typeof(OperationsStore))]
    [Migration("20260909184125_M3Operations")]
    partial class M3Operations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("operations")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFlow.Domain.People.Employee", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("OrganizationId", "Id");

                    b.ToTable("Employees", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.People.Vendor", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("OrganizationId", "Id");

                    b.ToTable("Vendors", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Building", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "PropertyId");

                    b.ToTable("Buildings", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Portfolio", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("OrganizationId", "Id");

                    b.ToTable("Portfolios", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Property", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "PortfolioId");

                    b.ToTable("Properties", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Space", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "BuildingId");

                    b.HasIndex("OrganizationId", "PropertyId");

                    b.ToTable("Spaces", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Timeline.TimelineEntry", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PreviousVendorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "WorkId", "OccurredAt");

                    b.ToTable("Timeline", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Work.WorkCategory", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("WorkCategories", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Work.WorkItem", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ScheduledEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ScheduledStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("WorkType")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "BuildingId");

                    b.HasIndex("OrganizationId", "CategoryId");

                    b.HasIndex("OrganizationId", "EmployeeId");

                    b.HasIndex("OrganizationId", "PropertyId");

                    b.HasIndex("OrganizationId", "SpaceId");

                    b.HasIndex("OrganizationId", "VendorId");

                    b.ToTable("WorkItems", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Building", b =>
                {
                    b.HasOne("PropFlow.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Property", b =>
                {
                    b.HasOne("PropFlow.Domain.Properties.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Properties.Space", b =>
                {
                    b.HasOne("PropFlow.Domain.Properties.Building", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Timeline.TimelineEntry", b =>
                {
                    b.HasOne("PropFlow.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Work.WorkItem", b =>
                {
                    b.HasOne("PropFlow.Domain.Properties.Building", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Domain.Work.WorkCategory", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Domain.People.Employee", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropFlow.Domain.Properties.Space", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Domain.People.Vendor", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VendorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
