// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFlow.Infrastructure.Persistence;

#nullable disable

namespace PropFlow.Infrastructure.Persistence.Migrations.Operations
{
    [DbContext(typeof(OperationsStore))]
    partial class OperationsStoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("operations")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFlow.Domain.People.Vendor", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("OrganizationId", "Id");

                    b.ToTable("Vendors", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Timeline.TimelineEntry", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PreviousVendorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "WorkId", "OccurredAt");

                    b.ToTable("Timeline", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Work.WorkItem", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "VendorId");

                    b.ToTable("WorkItems", "operations");
                });

            modelBuilder.Entity("PropFlow.Domain.Timeline.TimelineEntry", b =>
                {
                    b.HasOne("PropFlow.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Work.WorkItem", b =>
                {
                    b.HasOne("PropFlow.Domain.People.Vendor", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VendorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
